before_install:
  - gem update --system
  - gem update bundler
rvm:
  - 2.2.9
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - rbx-2
  - ruby-head
  - jruby-9.0.5.0
  - jruby-9.1.17.0
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx-2
# Send builds to container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
